concurrent = 1

check_interval = 0

shutdown_timeout = 0



[session_server]

  session_timeout = 1800



[[runners]]

  name = "1st_runner"

  url = "https://gitlab.com/"

  id = 25086067

  token = "pXkirAjFxwBuatjg_6is"

  token_obtained_at = 2023-07-10T16:30:10Z

  token_expires_at = 0001-01-01T00:00:00Z

  executor = "docker"

  [runners.cache]

    MaxUploadedArchiveSize = 0

  [runners.docker]

    tls_verify = false

    clone_url = "http://gitlab.example.local"

    image = "alpine"

    privileged = true

    disable_entrypoint_overwrite = false

    oom_kill_disable = false

    disable_cache = false

    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]



    shm_size = 0

