image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - release
  - deploy

variables:
   
  CONTAINER_TEST_IMAGE: gitlab-repo:latest
  CONTAINER_RELEASE_IMAGE: gitlab-repo:latest

before_script:
  - docker login -u mahtabhj -p 542565mhj



build:
  stage: build
  script:
    - docker build -t gitlab-repo .
    - docker tag $CONTAINER_TEST_IMAGE mahtabhj/$CONTAINER_TEST_IMAGE
    - docker push mahtabhj/$CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull mahtabhj/$CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE npm test


release-image:
  stage: release
  script:
    - docker pull mahtabhj/$CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE mahtabhj/$CONTAINER_RELEASE_IMAGE
    - docker push mahtabhj/$CONTAINER_RELEASE_IMAGE
  

deploy:
  stage: deploy
  script:
    - docker pull mahtabhj/$CONTAINER_RELEASE_IMAGE
    - docker run -d -p 3000:3000 mahtabhj/$CONTAINER_RELEASE_IMAGE
   
